henrikalbrecht/I05-Virtuelle-Maschinen

- .gitignore
- README.md
- docs/_includes/default-attributes.inc.adoc
- docs/project_management/iteration_plan_01.adoc
- docs/requirements/vision.adoc
_.gitignore_
- added _.vscode_ to ignore list
_default-attributes.inc.adoc_
- set attributes in accordance with project properties
:project-name: I05 - Vergabe von Virtuellen Maschinen
:project-system-name: Verwaltungssystem
_iteration_plan_01.adoc_
- added contact information
- added time frame to table "Meilensteine"
> general info and workspace settings

- docs/requirements/vision.adoc
- added Stakeholder "Projektgruppe" 
- changed Stakeholder "Auftraggeber/Admin" to "Christoph Zirkelbach" 
- removed Stakeholder "Softwareentwicklungsteam" 
- added "Email Templates verwalten" as "Hauptfunktion"
see #14
> update vision, Stakeholder

- docs/requirements/vision.adoc
- add workplace to "Benutzerumgebung"
- remove sample description
> add workplace to "Benutzerumgebung"

- docs/project_management/iteration_plan_02.adoc
fully drafted iteration plan 02
there shouldn't be any major inconsistencies left
> full draft of iteration plan 02

- docs/project_management/project_plan.adoc
- rephrased and updated sections
- added iterations and milestones
> Project plan

- docs/requirements/use-case_model.adoc
Tabelle in richtiger Reihenfolge und formatiert (use-case_model.adoc
> Update Use Case model

- docs/project_management/project_plan.adoc
- moved milestone "risk list" from I2 to I3
- updated target velocity for every iteration to 14 (length of each iteration)
> moved risk list and updated target velocity

- docs/project_management/iteration_plan_02.adoc
see last comment on #10 
- **removed** section "Meilensteine"
- **updated** problems to new naming scheme
- **updated** Aufgabenzuordnung with new Github link
> Iteration Plan 02 needed update

- docs/project_management/responsibilities.adoc
Added backup roles to the responsibilities file.
> Add backup roles

- docs/project_management/iteration_plan_03.adoc
- drafted a preliminary version of iteration plan 03
- need to talk with coach during meeting about it
- assessment needs to be done at the end of iteration 03, only then can the document be finalized
> preliminary draft of iteration 03

- docs/requirements/vision.adoc
added "zusätzliche Produktanforderungen" in preparation of systemwide-requirements
> update zusätzliche Anforderungen

- docs/requirements/system-wide_requirements.adoc
- drafted first version of system-wide requirements
- *Organisatorische Randbedingungen* and *Rechtliche Anforderungen* will be discussed during next meeting with PO
> first draft of system-wide requirements

- src/docker/dockerfiles/dockerfile
This dockerfile builds a dev dockerimage that uses ubuntu as base and contains our required software: python, django, react, javascript, postgresql
How to create the image:
`docker build -t dev_image .`
How to use Image:
`docker run -it -v -p 8000:8000 <absolute_path_to_workspace_directory>:/app dev_image`
Create Django Starting Files:
`django-admin startproject <project_name>`
Run Django Server inside of the image:
`python3 manage.py runserver 0.0.0.0:8000`
> Add dev Dockerfile

- src/docker/dockerfiles/dockerfile
#64 Take a look at the previous PR for the commands that allow you to start developing.
> Add nvm and django dependencies to enable next.js react development and django development

- docs/project_management/risk_list.adoc
fix risk list csv include to refer to the correct risk list
> fix risk list csv include

- docs/requirements/use-case_model.adoc
removed unused header elements, added uc03, added references
> Dokusprint Use Case Model

- docs/requirements/system-wide_requirements.adoc
harmonized with project advertisement document and incorporated small changes
> Dokusprint Systemwide Requirements

- docs/project_management/project_plan.adoc
- docs/project_management/responsibilities.adoc
Updated project plan:
- added remaining iterations
- added deployment
- added lessons learned
Updated responsibilities
> Dokusprint projectplan

- docs/project_management/iteration_plan_02.adoc
- docs/project_management/iteration_plan_03.adoc
- docs/project_management/iteration_plan_04.adoc
Finalized Iteration plans 02 and 03
> Dokusprint iteration plans

- belegabgabe_se1/se1_belegabgabe_t00.adoc
- docs/project_management/responsibilities.adoc
- First version of final "Abgabetemplate"
- I already found some issues in various documents which I will fix tomorrow
> Projektabgabe - first version of final "Abgabetemplate"

- docs/architecture/architecture_notebook.adoc
- docs/project_management/iteration_plan_02.adoc
- docs/project_management/iteration_plan_03.adoc
- docs/project_management/project_plan.adoc
- docs/project_management/risk_list.adoc
- docs/requirements/domain_model.adoc
- docs/requirements/glossary.adoc
- docs/requirements/use-case_model.adoc
- docs/requirements/vision.adoc
- docs/test/test_cases.adoc
FORMATTING: added forced page breaks and image captions for better readbility
> FORMATTING: added forced page breaks and image captions

- docs/project_management/iteration_plan_02.adoc
- docs/project_management/iteration_plan_03.adoc
- docs/project_management/project_plan.adoc
- docs/project_management/risk_list.adoc
- docs/requirements/glossary.adoc
- docs/requirements/use_case_01.inc.adoc
- docs/requirements/use_case_03.inc.adoc
- docs/requirements/vision.adoc
more page breaks and table/column sizing corrections
> more page breaks and table/column sizing corrections
